### ISSUE TITLE
[Suggestion]: Migrate to PBandJ

### ISSUE THREAD

**Issue by moishinetzer** [HelipengTony/nexment#12]
Given tsdx isn't maintained anymore and is very inefficient to todays standards, it may make sense to migrate to PBandJ:

https://github.com/moishinetzer/pbandj

It also includes config for vitest, changesets for publishing and other modern features and tools such as storybook v7 etc.

I'm happy to help make the transition if you need any help!

**Comment by ttttonyhe** [comment]
Appreciate it, but no thank you! I'd prefer to keep it dead simple. Plus this project is not actively maintained.
